- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Rahim,Robert"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ persons | split(',') }}"

  - name: convert map into list
    vars:
      course: 
        name: Ansible
        duration: 10HR
        trainer: Sivakumar
    ansible.builtin.debug:
      msg: " Course Info:{{ course | dict2items}}"

  - name: convert list into dictionary
    vars:
      course: 
       - {'key': 'name', 'value': 'Ansible'}
       - {'key': 'duration', 'value': '10HR'}
       - {'key': 'trainer', 'value': 'Sivakumar'}
    ansible.builtin.debug:
      msg: " Course Info:{{ course | items2dict}}"