- name: functions
  hosts: local
  connection: local
  vars:
    persons: "Ramesh,Suresh,Rahim,Robert"
  tasks:
  - name: check undefined variable
    ansible.builtin.debug:
      msg: "Hello, {{ persons | split(',') }}" 