- name: Install packages
  hosts: frontend
  become: yes
  tasks:
  - name: Install packages
    ansible.builtin.package:
      name: "{{ item.name }}"
      state: "{{ item.value }}"
    loop:
    - { name: 'mysql', state: 'absent' }
    - { name: 'nginx', state: 'present' }
    - { name: 'zip', state: 'absent' }  