- name: install nginx
  hosts: frontend
  become: yes
  serial: 5
  tasks:
    - name: Install nginx
      ansible.builtin.dnf:
        name: nginx
        state: installed

    - name: run nginx
      ansible.builtin.service:
        name: nginx
        state: started
        enabled: yes
