- name: user creation
  hosts: local
  connection: local
  tasks:
    - name: check if roboshop user exists or not
      ansible.builtin.command: id roboshop
      register: output
      ignore_errors: true

    - name: create user
      become: yes
      ansible.builtin.command: useradd roboshop
      when: output.rc != 0

    - name: User already exists
      ansible.builtin.debug:
        msg: "user already exists"
      when: output.rc == 0
