- name: variables from inventory
  hosts: frontend
  tasks:
  - name: print course information
    ansible.builtin.debug:
      msg: "Hello i am learning {{ COURSE }}, Course Duration: {{ DURATION }}, Trainer is {{ TRAINER }}"